# Generated by Django 3.2.4 on 2021-07-25 03:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('username', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='', max_length=20)),
                ('email', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('property_type', models.CharField(max_length=30)),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('lotAreaUnit', models.CharField(default='', max_length=20)),
                ('lotAreaValue', models.IntegerField()),
                ('zpid', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photo_main', models.ImageField(upload_to='static/images/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
        ),
    ]
