# Generated by Django 3.2.4 on 2021-07-08 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('property_type', models.CharField(max_length=30)),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('zpid', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='static/images/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
