# Generated by Django 3.2.4 on 2021-07-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_property_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
